// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdUrwo4so5MjNE2tbYIzOrNAMmmRhQ-o',
    appId: '1:1005990363308:web:49e35949f9fedc5e7ddf09',
    messagingSenderId: '1005990363308',
    projectId: 'hopepaw-170d4',
    authDomain: 'hopepaw-170d4.firebaseapp.com',
    storageBucket: 'hopepaw-170d4.firebasestorage.app',
    measurementId: 'G-VZGDBEYQQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8mAj5QVZ82fDe-p3_IM9lLPvrvIAoFo',
    appId: '1:1005990363308:android:686aee5428c4193e7ddf09',
    messagingSenderId: '1005990363308',
    projectId: 'hopepaw-170d4',
    storageBucket: 'hopepaw-170d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmp1PKxgFvhaJeNsWg0uSAvlXZJVTRZI',
    appId: '1:1005990363308:ios:d0300b8434ac6e507ddf09',
    messagingSenderId: '1005990363308',
    projectId: 'hopepaw-170d4',
    storageBucket: 'hopepaw-170d4.firebasestorage.app',
    iosBundleId: 'com.example.hopepaw',
  );
}
